# Cloudflare Pages 配置文件
name = "tool-hub"
compatibility_date = "2024-01-01"

[build]
command = "npm run build:cloudflare"
cwd = "."
publish = "dist"

[build.environment_variables]
NODE_VERSION = "18"

# 页面规则
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# 头部规则
[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.json"
[headers.values]
Cache-Control = "public, max-age=86400"

[[headers]]
for = "/"
[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"